### ISSUE TITLE
[Unraid][Docker] struct.error: unpack requires a string argument of length 28

### ISSUE THREAD

**Issue by janabimustafa** [ninthwalker/DashBtn#1]
log file:

```
Traceback (most recent call last):
File "/config/dashbtn.py", line 32, in <module>
arp_detailed = struct.unpack('2s2s1s1s2s6s4s6s4s', arp_header)
struct.error: unpack requires a string argument of length 28

python exited 1
```
I am getting this error every night, and it causes the docker container instance to be shut down.

**Comment by ninthwalker** [comment]
Thanks for the pull request. I hadn't experienced the error, Probably partly depends on the devices that are on the network sending packets.
