### ISSUE TITLE
Still usable?

### ISSUE THREAD

**Issue by Bretthansenpc** [ninthwalker/DashBtn#3]
im trying to figure out what im doing wrong ive connected my dashbutton to the network but it doesnt want to execlute the .sh that i have it doesnt really show anything in the logs either

**Comment by ninthwalker** [comment]
Works for me.
Did you make your script executable? I'm assuming its sitting in a mapped location to the docker?
If you just run the script by itself does it work? make sure you modify the docker to include the mac address of the button as well

**Comment by ninthwalker** [comment]
Closing for now
